#!/bin/sh

set -x

(cd basic ; ./Allwmake)
(cd incompressible ; ./Allwmake)
(cd heatTransfer ; ./Allwmake)
(cd compressible ; ./Allwmake)
(cd combustion ; ./Allwmake)
(cd DNSandLES ; ./Allwmake)
(cd multiphase ; ./Allwmake)
(cd electromagnetics ; ./Allwmake)
(cd stressAnalysis ; ./Allwmake)
(cd financial ; ./Allwmake)
