package FoamXServer.CasePostServer;


/**
* FoamXServer/CasePostServer/ICasePostServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public interface ICasePostServer extends ICasePostServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICasePostServer
