package FoamXServer.CasePostServer;


/**
* FoamXServer/CasePostServer/ICasePostServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 22 June 2005 14:41:58 o'clock BST
*/


// ---------------------------------------------------------------------
public interface ICasePostServer extends ICasePostServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ICasePostServer
