package FoamXServer;


/**
* FoamXServer/BoolListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 02 April 2007 10:12:21 o'clock BST
*/

public final class BoolListHolder implements org.omg.CORBA.portable.Streamable
{
  public boolean value[] = null;

  public BoolListHolder ()
  {
  }

  public BoolListHolder (boolean[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.BoolListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.BoolListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.BoolListHelper.type ();
  }

}
