package FoamXServer;

/**
* FoamXServer/FoamXIOErrorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 02 April 2007 10:12:21 o'clock BST
*/

public final class FoamXIOErrorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.FoamXIOError value = null;

  public FoamXIOErrorHolder ()
  {
  }

  public FoamXIOErrorHolder (FoamXServer.FoamXIOError initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.FoamXIOErrorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.FoamXIOErrorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.FoamXIOErrorHelper.type ();
  }

}
