package FoamXServer;


/**
* FoamXServer/FoamXAny.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 03 March 2005 22:12:52 o'clock GMT
*/


// -------------------------------------------------------------------------
public final class FoamXAny implements org.omg.CORBA.portable.IDLEntity
{
  public FoamXServer.FoamXType type = null;
  public org.omg.CORBA.Any value = null;

  public FoamXAny ()
  {
  } // ctor

  public FoamXAny (FoamXServer.FoamXType _type, org.omg.CORBA.Any _value)
  {
    type = _type;
    value = _value;
  } // ctor

} // class FoamXAny
