package FoamXServer;


/**
* FoamXServer/StringPair.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 03 March 2005 22:12:52 o'clock GMT
*/

public final class StringPair implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String value = null;

  public StringPair ()
  {
  } // ctor

  public StringPair (String _name, String _value)
  {
    name = _name;
    value = _value;
  } // ctor

} // class StringPair
