package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IBoundaryTypeDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public final class IBoundaryTypeDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IBoundaryTypeDescriptor value = null;

  public IBoundaryTypeDescriptorHolder ()
  {
  }

  public IBoundaryTypeDescriptorHolder (FoamXServer.CaseServer.IBoundaryTypeDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IBoundaryTypeDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IBoundaryTypeDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IBoundaryTypeDescriptorHelper.type ();
  }

}
