package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IBoundaryTypeDescriptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public interface IBoundaryTypeDescriptorOperations 
{

  //- Boundary type name (eg, "slip").
  String name ();

  //- Boundary type name (eg, "slip").
  void name (String newName);
  String displayName ();
  void displayName (String newDisplayName);
  String description ();
  void description (String newDescription);
  String patchType ();
  void patchType (String newPatchType);
  String superType ();
  void superType (String newSuperType);
  FoamXServer.StringPair[] patchFieldTypes ();
  void patchFieldTypes (FoamXServer.StringPair[] newPatchFieldTypes);
} // interface IBoundaryTypeDescriptorOperations
