package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IGeometricFieldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 22 June 2005 14:41:58 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IGeometricFieldOperations 
{
  String name ();
  void getInternalFieldValue (FoamXServer.IDictionaryEntryHolder internalFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;
  void getPatchFieldParameters (String patchName, FoamXServer.IDictionaryEntryHolder patchFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;

  // Returns true if this has been modified
  boolean modified ();
} // interface IGeometricFieldOperations
