package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IGeometricFieldOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public interface IGeometricFieldOperations 
{
  String name ();
  void getInternalFieldValue (FoamXServer.IDictionaryEntryHolder internalFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;

  //) raises(FoamXError, FoamXIOError);
  void getPatchFieldParameters (String patchName, FoamXServer.IDictionaryEntryHolder patchFieldValue) throws FoamXServer.FoamXError, FoamXServer.FoamXIOError;

  // Returns true if this has been modified
  boolean modified ();
} // interface IGeometricFieldOperations
