package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IGeometricFieldDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public final class IGeometricFieldDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IGeometricFieldDescriptor value = null;

  public IGeometricFieldDescriptorHolder ()
  {
  }

  public IGeometricFieldDescriptorHolder (FoamXServer.CaseServer.IGeometricFieldDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IGeometricFieldDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IGeometricFieldDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IGeometricFieldDescriptorHelper.type ();
  }

}
