package FoamXServer.CaseServer;

/**
* FoamXServer/CaseServer/IPatchDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public final class IPatchDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.CaseServer.IPatchDescriptor value = null;

  public IPatchDescriptorHolder ()
  {
  }

  public IPatchDescriptorHolder (FoamXServer.CaseServer.IPatchDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.CaseServer.IPatchDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.CaseServer.IPatchDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.CaseServer.IPatchDescriptorHelper.type ();
  }

}
