package FoamXServer.CaseServer;


/**
* FoamXServer/CaseServer/IPatchDescriptorOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// ---------------------------------------------------------------------
public interface IPatchDescriptorOperations 
{

  //- Name of patch type (eg, "wall").
  String name ();

  //- Name of patch type (eg, "wall").
  void name (String newName);

  //- Display name (eg, "Wall").
  String displayName ();

  //- Display name (eg, "Wall").
  void displayName (String newDisplayName);

  //- Description (eg, "Solid Wall").
  String description ();

  //- Description (eg, "Solid Wall").
  void description (String newDescription);

  //- Valid patch field types for this patch type.
  String[] patchFieldTypes ();

  //- Valid patch field types for this patch type.
  void patchFieldTypes (String[] newPatchFieldTypes);
} // interface IPatchDescriptorOperations
