#!/bin/sh

find . -name "*.cfg" | \
  xargs grep iconURL | \
  cut -d'"' -f2 | \
  cut -d/ -f6 | \
  sort -u > iconList

echo "Missing icons" > missingIconList
echo "~~~~~~~~~~~~~" > missingIconList

CURRENT_ICONS=`ls -1 ../Java/FoamX/icons/small/maths`

for f in `cat iconList`
do
    MATCH="NO"
    for i in $CURRENT_ICONS
    do
        if [ "$f" = "$i" ] ; then
            MATCH="YES"
        fi
    done
    if [ "$MATCH" = "NO" ] ; then
        echo "$f" >> missingIconList
    fi
done
