#!/bin/sh

set -x

wmake Lambda2
wmake Mach
wmake Q
wmake Ucomponents
wmake divU
wmake enstrophy
wmake magGradU
wmake magU
wmake streamFunction
wmake uprime
wmake vorticity
wmake Co
wmake Pe
wmake flowType
