#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
cases="pitzDaily pitzDaily3Blocks"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
done 


