package FoamXServer.HostBrowser;


/**
* FoamXServer/HostBrowser/IHostBrowserOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 22 June 2005 14:41:58 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IHostBrowserOperations 
{
  FoamXServer.HostDescriptor[] hosts ();
  void refreshHostList () throws FoamXServer.FoamXError;
  boolean isHostAlive (String hostName) throws FoamXServer.FoamXError;
  void hostIsAlive (String hostName) throws FoamXServer.FoamXError;
  void hostIsDead (String hostName) throws FoamXServer.FoamXError;
  void openCaseBrowser (String hostName) throws FoamXServer.FoamXError, FoamXServer.FoamXSYSError;
  boolean getCaseBrowserReference (String hostName, FoamXServer.CaseBrowser.ICaseBrowserHolder browserObj) throws FoamXServer.FoamXError, FoamXServer.FoamXSYSError;

  // Validation.
  void validate () throws FoamXServer.FoamXError, FoamXServer.FoamXIOError, FoamXServer.ValidationError;

  // Persistence.
  void save () throws FoamXServer.FoamXError, FoamXServer.FoamXIOError, FoamXServer.ValidationError;

  // Lifetime management.
  void close ();
} // interface IHostBrowserOperations
