#!/bin/sh
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2005 OpenCFD Ltd.
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#
# Script
#     makeWmake
#
# Description
#     Script to build all the system specific parts of wmake
#
#------------------------------------------------------------------------------

cd src ; make ; cd ..

rm -rf tcshScripts
mkdir tcshScripts

cd cshScripts

for file in *
do
    cat $file | sed s/csh/tcsh/ > ../tcshScripts/$file
    chmod ugo+rx ../tcshScripts/$file
done

cd ..

rm -rf bashScripts
mkdir bashScripts

cd kshScripts

for file in *
do
    cat $file | sed s/ksh/bash/ > ../bashScripts/$file
    chmod ugo+rx ../bashScripts/$file
done

cd ..

#------------------------------------------------------------------------------
