#!/bin/sh

set -x

wmake transformPoints
wmake rotateMesh
wmake checkMesh
wmake attachMesh
wmake zipUpMesh
wmake deformedGeom
wmake subsetMesh
wmake mirrorMesh
wmake flattenMesh
wmake mergeMeshes
wmake splitMesh
wmake renumberMesh
wmake tetDecomposition
wmake moveMesh
wmake moveDynamicMesh
wmake moveEngineMesh
wmake splitMeshRegions
wmake insideCells
wmake couplePatches
wmake stitchMesh
wmake autoPatch
wmake refineMesh
wmake objToVTK
wmake createPatch
wmake cellSet
wmake faceSet
wmake pointSet

(cd patchTool; ./Allwmake)
