/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[279] =
    {   0,
        0,    0,    0,    0,    6,    6,    0,    0,   17,   17,
       20,   18,   18,   18,   18,   18,   18,   18,   18,    3,
        3,    3,    3,    3,    3,    3,    3,    3,    6,    6,
        6,    6,    6,    6,   18,   18,   18,   18,   18,   14,
       18,   18,   18,   18,   18,   18,   18,   18,   18,   17,
       17,   17,   17,   17,   17,   17,   17,    0,    2,    0,
        0,    0,    0,    0,    0,    0,    4,    6,    2,    6,
        6,    6,    6,    6,    6,    0,    0,   14,    0,    0,
       15,    2,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   17,   17,    2,   17,   17,   17,

       17,   17,   17,   17,    0,    0,    1,    0,    0,    0,
        6,    6,    6,    0,    0,    0,   14,    0,    0,    0,
        0,    0,    0,    0,    0,   17,   17,    1,   17,   17,
       17,    0,    0,    0,    0,    6,    6,    0,    0,   15,
        0,    0,    0,   10,    0,    0,    0,    0,    0,    9,
        0,    0,    0,   12,    0,    0,    0,    0,   17,   17,
       17,   17,    0,    0,    0,    0,    6,    6,    0,   10,
        0,   10,    0,    0,    0,    8,    0,    9,    0,    9,
       12,    0,   12,    0,    0,    0,   11,    0,    0,    0,
       17,   17,   17,   17,    0,    0,    0,    0,    6,    6,

        0,   10,    8,    0,    8,    0,    9,   12,   11,    0,
       11,    0,    0,    0,   17,   17,   17,   17,    0,    0,
        0,    7,    6,    6,    0,    8,    0,   11,    0,    0,
        7,   17,   17,   17,    7,    0,    0,    6,    0,    0,
        0,   17,   17,    0,    0,    6,    0,    0,    0,    0,
       13,    0,   17,   17,    0,    5,    0,   13,    0,   13,
       17,    5,    0,    0,   13,   17,    0,    0,   17,    0,
        0,   17,    0,    0,   17,   16,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    1,    1,    1,    1,    9,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   10,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   11,    1,   12,   13,

       14,    1,   15,   16,   17,   18,    1,   19,   20,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[30] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[310] =
    {   0,
        0,    8,   11,   24,   40,   48,   65,    1,   20,   93,
      731,  810,  810,  722,   26,    4,   44,   94,  701,  810,
      810,  685,  678,   28,   99,  102,  103,  664,    0,    0,
       30,  110,  111,  662,   48,   52,  113,  114,  121,  124,
      125,  128,  132,  136,  140,  166,  182,  198,  141,    0,
        0,  675,   55,  152,  155,  160,  658,  673,  810,  651,
      161,  633,  171,  177,  626,  618,  810,    0,    0,  192,
      187,  616,  199,  602,  590,  145,  172,  177,  201,  596,
      595,  202,  214,  210,  213,  217,  218,  221,  243,  226,
      259,  275,  227,  242,    0,  596,    0,   52,  253,  577,

      254,  264,  570,  564,  577,  574,  810,  270,  559,  526,
      235,  535,  517,  274,  283,  291,  292,  254,  295,  299,
      303,  307,  335,  306,  311,  534,  134,    0,  321,  520,
      497,  510,  324,  486,  463,  457,  439,  336,  319,  326,
      343,  452,  349,  350,  356,  355,  363,  443,  364,  370,
      371,  436,  377,  378,  384,  393,  383,  265,  435,  345,
      414,  408,  415,  394,  388,  382,  372,  364,  396,  374,
      404,  408,  412,  367,  416,  420,  419,  360,  426,  432,
      346,  433,  439,  440,  340,  446,  447,  456,  451,  397,
      338,  463,  308,  284,  287,  466,  285,  328,  277,  467,

      464,  474,  270,  480,  481,  484,  491,  492,  244,  498,
      499,  508,  507,  519,  232,  509,  230,  473,  211,   88,
      200,  491,  199,  520,  520,  526,  525,  532,  535,  536,
      549,  186,  105,  184,  550,  181,  556,  559,  554,  560,
      565,  159,  570,  147,  574,  578,  576,  580,  148,  584,
      588,  597,  133,  604,  118,  810,  602,  108,  606,  610,
       20,    0,   27,  609,  616,   18,    9,  617,    2,  626,
      630,  631,  635,  641,  648,  810,  636,  810,  655,  660,
      665,  670,  675,  680,  685,  690,  694,  699,  704,  709,
      714,  719,  724,  729,  734,  739,  744,  749,  754,  759,

      764,  769,  774,  779,  784,  789,  794,  799,  804
    } ;

static yyconst short int yy_def[310] =
    {   0,
      279,  279,  280,  280,  281,  281,  278,    7,  282,  282,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  283,  283,
      283,  283,  283,  283,  284,  284,  284,  285,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  286,
      286,  286,  286,  286,  286,  286,  286,  278,  278,  287,
      278,  278,  278,  278,  278,  278,  278,  283,  283,  288,
      283,  283,  283,  283,  283,  284,  285,  284,  284,  285,
      285,  285,  289,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  286,  286,  286,  290,  286,  286,

      286,  286,  286,  286,  278,  287,  278,  278,  278,  278,
      288,  283,  283,  284,  289,  291,  289,  292,  284,  284,
      293,  294,  284,  284,  284,  286,  290,  286,  286,  286,
      286,  278,  278,  278,  278,  283,  283,  284,  291,  291,
      292,  295,  296,  292,  297,  284,  293,  298,  299,  293,
      294,  300,  301,  294,  302,  284,  284,  284,  286,  286,
      286,  286,  278,  278,  278,  278,  283,  283,  284,  295,
      296,  296,  297,  303,  304,  297,  284,  298,  299,  299,
      300,  301,  301,  302,  305,  306,  302,  284,  284,  284,
      286,  286,  286,  286,  278,  278,  278,  278,  283,  283,

      284,  296,  303,  304,  304,  284,  299,  301,  305,  306,
      306,  284,  284,  284,  286,  286,  286,  286,  278,  278,
      278,  278,  283,  283,  284,  304,  284,  306,  284,  284,
      284,  286,  286,  286,  286,  278,  278,  283,  284,  307,
      284,  286,  286,  278,  278,  283,  284,  307,  308,  309,
      307,  284,  286,  286,  278,  278,  284,  308,  309,  309,
      286,  286,  278,  284,  309,  286,  278,  284,  286,  278,
      284,  286,  278,  284,  286,  278,  284,    0,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,

      278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yyconst short int yy_nxt[840] =
    {   0,
      278,   13,   46,   14,   47,   61,   48,   61,   15,   16,
      278,   17,   21,   18,   22,  272,   15,   49,   23,   24,
       62,   51,  270,   52,   19,   25,   12,   26,   53,   27,
      269,   23,   24,   59,   60,   59,   60,   69,   70,  267,
       28,   30,   12,   14,   12,   61,  266,   63,   31,   32,
       12,   17,   12,   33,  128,   77,   31,   78,  106,   77,
       62,   78,   97,   98,   34,   35,   36,   12,   37,   12,
       35,   35,   38,   39,   40,   35,   41,   35,   35,   35,
       35,   35,   42,   43,   35,   35,   44,   35,   35,   45,
       35,   35,   35,   35,   54,   64,   55,   64,   56,   12,

       61,   53,   61,   61,   64,   63,   64,   66,  236,   57,
       65,   71,   73,   61,   64,   62,   79,  258,   62,   65,
       77,   77,   78,   81,  104,  242,   72,   74,   82,   83,
       78,   77,   77,   78,   78,   77,  128,   78,   85,   77,
      106,   78,   86,   77,  263,   78,   84,   77,   77,   78,
       78,  261,   77,   99,   78,   99,   99,  258,  101,   87,
       94,  102,   61,  102,   61,  255,   88,   89,  100,   89,
      253,  100,   61,   77,  108,   78,  103,   62,   64,   77,
       64,   81,   90,   89,   77,   91,   78,   62,   71,   77,
       61,   78,  244,   65,  107,  106,  106,  243,   90,   92,

       73,   92,   64,   72,  114,   77,  242,   78,   77,   77,
       78,   81,  238,  237,   93,   74,  107,   77,  106,   78,
       77,  116,   78,  117,   77,   77,   78,   78,   77,  118,
       78,  236,  121,   77,   77,   78,   78,  107,  106,  106,
      119,  122,  234,  120,   89,   94,   89,  124,  232,   77,
       77,   78,   78,  209,   99,   99,   99,  129,  142,   90,
       89,  143,  123,  144,  125,  102,   77,  102,   78,  100,
      100,   61,   77,  133,   78,   90,   92,  138,   92,  203,
      103,   77,   77,   78,   78,  107,   62,  106,  190,  223,
      116,   93,  117,  107,  107,  106,  106,  221,  116,  116,

      140,  117,   77,  219,   78,  145,   77,  148,   78,  218,
      149,  152,  150,   77,  153,   78,  154,  157,   77,  146,
       78,  107,   99,  106,  160,   61,  116,  164,  107,  222,
      106,  222,  158,  116,  217,  155,   89,  100,  156,  169,
       62,  215,   77,   77,   78,   78,   99,  142,  192,  209,
      143,   90,  144,  142,  142,  181,  143,  143,  172,  144,
      174,  100,   77,  175,   78,  176,  177,  148,  148,  178,
      149,  149,  150,  180,  148,  152,  203,  149,  153,  150,
      154,  152,  152,  170,  153,  153,  183,  154,  185,  200,
       77,  186,   78,  187,   89,   61,  188,  196,  199,  201,

       77,  189,   78,   77,   77,   78,   78,  198,  142,   90,
       62,  143,  142,  202,  197,  143,  174,  202,  195,  175,
      174,  176,  214,  175,  174,  205,   77,  175,   78,  176,
      148,  194,  193,  149,  206,  207,  148,  152,  191,  149,
      153,  207,  208,  152,  185,  181,  153,  186,  208,  187,
      185,  185,  178,  186,  186,  211,  187,   89,   77,  212,
       78,  170,  168,   77,   99,   78,  216,   61,  224,   61,
      222,   77,   90,   78,  235,  167,  235,  213,  142,  100,
      225,  143,  220,  202,  174,  174,  166,  175,  175,  226,
      226,   77,  222,   78,  222,  148,  152,  227,  149,  153,

      207,  208,  185,  185,  165,  186,  186,  228,  228,   89,
       99,   89,   99,  163,   77,   77,   78,   78,  162,  230,
      231,  224,  231,  222,  229,  233,   77,   77,   78,   78,
      174,  161,   77,  175,   78,  226,  185,  159,  137,  186,
      239,  228,   77,   77,   78,   78,  136,  135,  240,  241,
      231,  235,  231,  235,   94,  239,   77,  245,   78,  245,
      246,   77,  245,   78,  249,  247,  252,  250,  252,  251,
      134,  254,   77,  254,   78,  245,  107,  245,  256,  246,
      132,  245,  256,   77,  249,   78,  131,  250,  249,  251,
      130,  250,  249,  260,  257,  250,  104,  251,  252,  126,

      252,  256,   77,   77,   77,  254,   78,  254,  262,   77,
      249,   78,  113,  250,  249,  265,   77,  250,   78,  265,
      249,  268,  112,  250,   77,  265,   78,  273,  264,  273,
      271,  274,  275,  274,  275,   75,  273,   77,  273,   78,
      110,  276,  274,   77,  274,   78,  109,  277,   77,  275,
       78,  275,   66,  107,  276,   12,   12,   12,   12,   12,
       20,   20,   20,   20,   20,   29,   29,   29,   29,   29,
       50,   50,   50,   50,   50,   68,  105,  104,   96,   68,
       76,   75,   76,   66,   76,   80,   67,   80,   58,   80,
       95,   95,   95,   95,  106,  106,  106,  106,  106,  111,

      111,  111,  111,  111,  115,  115,  115,  115,  115,  127,
      127,  127,  127,  127,  139,  139,  139,  139,  139,  141,
       66,  141,  141,  141,  147,   58,  147,  147,  147,  151,
      278,  151,  151,  151,  142,  278,  142,  142,  142,  171,
      278,  171,  171,  171,  173,  278,  173,  173,  173,  148,
      278,  148,  148,  148,  179,  278,  179,  179,  179,  152,
      278,  152,  152,  152,  182,  278,  182,  182,  182,  184,
      278,  184,  184,  184,  174,  278,  174,  174,  174,  204,
      278,  204,  204,  204,  185,  278,  185,  185,  185,  210,
      278,  210,  210,  210,  248,  278,  248,  248,  248,  249,

      278,  249,  249,  249,  259,  278,  259,  259,  259,   11,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yyconst short int yy_chk[840] =
    {   0,
        0,    1,    8,    1,    8,   16,    8,   16,    1,    2,
        0,    2,    3,    2,    3,  269,    2,    8,    3,    3,
       16,    9,  267,    9,    2,    4,    9,    4,    9,    4,
      266,    4,    4,   15,   15,   24,   24,   31,   31,  263,
        4,    5,    5,    5,    5,   17,  261,   17,    5,    6,
        6,    6,    6,    6,   98,   35,    6,   35,   98,   36,
       17,   36,   53,   53,    6,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,   10,   18,   10,   18,   10,   10,

       25,   10,   25,   26,   27,   26,   27,  220,  220,   10,
       18,   32,   33,   32,   33,   25,   37,  258,   26,   27,
       37,   38,   37,   38,  233,  233,   32,   33,   39,   39,
       39,   40,   41,   40,   41,   42,  127,   42,   42,   43,
      127,   43,   43,   44,  255,   44,   41,   45,   49,   45,
       49,  253,   76,   54,   76,   54,   55,  249,   55,   44,
       49,   56,   61,   56,   61,  244,   45,   46,   54,   46,
      242,   55,   63,   46,   63,   46,   56,   61,   64,   77,
       64,   77,   46,   47,   78,   47,   78,   63,   71,   47,
       71,   47,  236,   64,   70,   70,   70,  234,   47,   48,

       73,   48,   73,   71,   79,   48,  232,   48,   79,   82,
       79,   82,  223,  221,   48,   73,   83,   84,   83,   84,
       85,   83,   85,   83,   86,   87,   86,   87,   88,   84,
       88,  219,   87,   90,   93,   90,   93,  111,  111,  111,
       85,   88,  217,   86,   89,   90,   89,   93,  215,   94,
       89,   94,   89,  209,   99,  101,   99,  101,  118,   89,
       91,  118,   91,  118,   94,  102,   91,  102,   91,   99,
      101,  108,  158,  108,  158,   91,   92,  114,   92,  203,
      102,  114,   92,  114,   92,  115,  108,  115,  158,  199,
      115,   92,  115,  116,  117,  116,  117,  197,  116,  117,

      116,  117,  119,  195,  119,  119,  120,  121,  120,  194,
      121,  122,  121,  124,  122,  124,  122,  124,  125,  120,
      125,  139,  129,  139,  129,  133,  139,  133,  140,  198,
      140,  198,  125,  140,  193,  122,  123,  129,  123,  138,
      133,  191,  123,  138,  123,  138,  160,  141,  160,  185,
      141,  123,  141,  143,  144,  181,  143,  144,  143,  144,
      145,  160,  146,  145,  146,  145,  146,  147,  149,  178,
      147,  149,  147,  149,  150,  151,  174,  150,  151,  150,
      151,  153,  154,  170,  153,  154,  153,  154,  155,  168,
      157,  155,  157,  155,  156,  164,  156,  164,  167,  169,

      156,  157,  156,  169,  190,  169,  190,  166,  171,  156,
      164,  171,  172,  171,  165,  172,  173,  172,  163,  173,
      175,  173,  190,  175,  176,  175,  177,  176,  177,  176,
      179,  162,  161,  179,  177,  179,  180,  182,  159,  180,
      182,  180,  182,  183,  184,  152,  183,  184,  183,  184,
      186,  187,  148,  186,  187,  186,  187,  188,  189,  188,
      189,  142,  137,  188,  192,  188,  192,  196,  200,  196,
      200,  201,  188,  201,  218,  136,  218,  189,  202,  192,
      201,  202,  196,  202,  204,  205,  135,  204,  205,  204,
      205,  206,  222,  206,  222,  207,  208,  206,  207,  208,

      207,  208,  210,  211,  134,  210,  211,  210,  211,  212,
      216,  212,  216,  132,  213,  212,  213,  212,  131,  213,
      214,  224,  214,  224,  212,  216,  214,  225,  214,  225,
      226,  130,  227,  226,  227,  226,  228,  126,  113,  228,
      225,  228,  229,  230,  229,  230,  112,  110,  227,  230,
      231,  235,  231,  235,  229,  229,  231,  237,  231,  237,
      238,  239,  238,  239,  240,  239,  241,  240,  241,  240,
      109,  243,  241,  243,  241,  245,  106,  245,  245,  246,
      105,  246,  246,  247,  248,  247,  104,  248,  250,  248,
      103,  250,  251,  250,  247,  251,  100,  251,  252,   96,

      252,  252,   81,   80,  252,  254,  252,  254,  254,  257,
      259,  257,   75,  259,  260,  259,  264,  260,  264,  260,
      265,  264,   74,  265,  268,  265,  268,  270,  257,  270,
      268,  271,  272,  271,  272,   72,  273,  271,  273,  271,
       66,  273,  274,  277,  274,  277,   65,  274,  274,  275,
      274,  275,   62,   60,  275,  279,  279,  279,  279,  279,
      280,  280,  280,  280,  280,  281,  281,  281,  281,  281,
      282,  282,  282,  282,  282,  283,   58,   57,   52,  283,
      284,   34,  284,   28,  284,  285,   23,  285,   22,  285,
      286,  286,  286,  286,  287,  287,  287,  287,  287,  288,

      288,  288,  288,  288,  289,  289,  289,  289,  289,  290,
      290,  290,  290,  290,  291,  291,  291,  291,  291,  292,
       19,  292,  292,  292,  293,   14,  293,  293,  293,  294,
       11,  294,  294,  294,  295,    0,  295,  295,  295,  296,
        0,  296,  296,  296,  297,    0,  297,  297,  297,  298,
        0,  298,  298,  298,  299,    0,  299,  299,  299,  300,
        0,  300,  300,  300,  301,    0,  301,  301,  301,  302,
        0,  302,  302,  302,  303,    0,  303,  303,  303,  304,
        0,  304,  304,  304,  305,    0,  305,  305,  305,  306,
        0,  306,  306,  306,  307,    0,  307,  307,  307,  308,

        0,  308,  308,  308,  309,    0,  309,  309,  309,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278,  278,
      278,  278,  278,  278,  278,  278,  278,  278,  278
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wmkdep.l"
#define INITIAL 0
#line 2 "wmkdep.l"
/*----------------------------------------------------------------------------*\
 =========                   |
 \\      /   F ield          | OpenFOAM: The Open Source CFD Toolbox
  \\    /    O peration      |
   \\  /     A nd            | Copyright (C) 1991-2005 OpenCFD Ltd.
    \\/      M anipulation   |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Application
    wmkdep

Description
     A fast dependency list generator which emulates the behaviour and
     output of cpp -M. However, the output contains no duplications and 
     is ~40% faster than cpp.

     The algorithm uses flex to scan for includes and searches the files
     found.  Each file is entererd into a hash table so that files are
     scaned only once.  This is why this program is faster than cpp.

Usage
    wmkdep [ -Idirectory ... -Idirectory] filename

\*----------------------------------------------------------------------------*/

#define FILE_STACK_SIZE 300
#define HASH_TABLE_SIZE 500

#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <dirent.h>

void nextFile(const char* fileName);
void importFile(const char* fileName);
void importDirectory(const char* dirName);

#   undef yywrap	/* sometimes a macro by default */

#define CMNT 1
#define CFNAME 2
#define JFNAME 3
#define FFNAME 4

#line 703 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 "wmkdep.l"


#line 860 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 279 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 810 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "wmkdep.l"
;             /* remove c++ style one line comments */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "wmkdep.l"
BEGIN(CMNT);    /* start removing c style comment */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "wmkdep.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "wmkdep.l"
BEGIN(INITIAL); /* end removing c style comment */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "wmkdep.l"
BEGIN(CFNAME);  /* c-file name */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "wmkdep.l"
{ BEGIN(INITIAL); nextFile(yytext); } /*"*/
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "wmkdep.l"
BEGIN(JFNAME);  /* java-file name */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "wmkdep.l"
{ BEGIN(INITIAL); importFile(yytext); } /*"*/
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "wmkdep.l"
{ BEGIN(INITIAL); importDirectory(yytext); } /*"*/
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "wmkdep.l"
BEGIN(FFNAME);  /* FORTRAN-file name */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "wmkdep.l"
{ BEGIN(INITIAL); nextFile(yytext); } /*'*/
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "wmkdep.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "wmkdep.l"
ECHO;
	YY_BREAK
#line 1039 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMNT):
case YY_STATE_EOF(CFNAME):
case YY_STATE_EOF(JFNAME):
case YY_STATE_EOF(FFNAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 279 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 279 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 278);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 86 "wmkdep.l"



int nDirectories;
char** directories;
char* sourceFile = NULL;
char* sourceExt = NULL;
char* objectFile = NULL;
char* classFile = NULL;
char* depFile = NULL;

int main(int argc, char* argv[])
{
    char *dotPtr, *slashPtr;
    int i;

    if (argc == 1)
    {
        fprintf(stderr,"input file not supplied\n");
        exit(1);
    }

    sourceFile = (char*)malloc(strlen(argv[argc-1]) + 1);
    strcpy(sourceFile, argv[argc-1]);
    fprintf(stderr,"Making dependency list for source file %s\n", sourceFile);
    
    
    /* Get list of -I directories. */
    nDirectories = 0;

    for (i = 1; i < argc; i++)
    {
        if (strncmp(argv[i], "-I", 2) == 0)
        {
            nDirectories++;
        }
    }

    directories = (char**)malloc(sizeof(char*)*nDirectories);

    nDirectories = 0;

    for (i = 1; i < argc; i++)
    {
        if (strncmp(argv[i], "-I", 2) == 0)
        {
            directories[nDirectories++] = strdup(argv[i] + 2);
        }
    }



    if ((dotPtr = strrchr(sourceFile, '.')) == NULL)
    {
        fprintf
        (
            stderr,
            "Cannot find extension in source file name %s\n",
            sourceFile
        );
        exit(1);
    }

    if ((slashPtr = strrchr(sourceFile, '/')) == NULL)
    {
        slashPtr = sourceFile;
    }
    else
    {
        slashPtr++;
    }

    sourceExt = (char*)malloc(strlen(sourceFile));
    sourceExt[0] = 0;
    strncat
    (
        sourceExt,
        dotPtr+1,
        (&sourceFile[strlen(sourceFile) - 1] - dotPtr)/sizeof(char)
    );

    /* initialise depFile to zero and use strncat rather than strncpy
       because there is a bug in the SGI strncat that if 0 preceeds the .
       it inserts a space */
    depFile = (char*)malloc(strlen(sourceFile) + 3);
    depFile[0] = 0;
    strncat(depFile, sourceFile, (dotPtr - sourceFile)/sizeof(char));
    strcat(depFile, ".dep");

    if (strcmp(sourceExt, "java") == 0)
    {
        classFile = (char*)malloc(strlen(sourceFile) + 17);
        strcpy(classFile, "$(CLASSES_DIR)/");
        strncat(classFile, sourceFile, (dotPtr - sourceFile)/sizeof(char));
        strcat(classFile, ".class");

        printf("%s: %s\n", classFile, depFile);
    }
    else
    {
        objectFile = (char*)malloc(strlen(sourceFile) + 16);
        strcpy(objectFile, "$(OBJECTS_DIR)/");
        strncat(objectFile, slashPtr, (dotPtr - slashPtr)/sizeof(char));
        strcat(objectFile, ".o");

        printf("%s: %s\n", objectFile, depFile);
    }

    nextFile(sourceFile);
    yylex();


    for (i = 0; i < nDirectories; i++)
    {
        free(directories[i]);
    }
    free(directories);

    free(sourceFile);
    free(sourceExt);
    free(objectFile);
    free(classFile);
    free(depFile);

    return 0;
}


int currentBuffer = 0;                     /* Buffer pointer stack counter */
YY_BUFFER_STATE buffers[FILE_STACK_SIZE];  /* Buffer pointer stack */

/* file name entry in hash table */

struct FileName
{
    char* name;
    struct FileName* next;
};

struct FileName* fileHashTable[HASH_TABLE_SIZE];   /* File hash table */
struct FileName* dirHashTable[HASH_TABLE_SIZE];    /* Directory hash table */


/* lookup name in hash table, if not found insert in table */

int lookUp(struct FileName** hashTable, const char* p)
{
    int ii = 0;
    struct FileName* n;
    struct FileName* nn;

    /* hash */
    const char* pp = p;
    while (*pp) ii = ii<<1 ^ *pp++;
    if (ii < 0) ii = -ii;
    ii %= HASH_TABLE_SIZE;

    /* search */
    for (n=hashTable[ii]; n; n=n->next)
    {
        if (strcmp(p, n->name) == 0)
        {
            /* entry found so return true */
            return 1;
        }
    }

    /* insert */
    nn = (struct FileName*)malloc(sizeof(struct FileName));
    nn->name = (char*)malloc(strlen(p)+1);
    strcpy(nn->name, p);
    nn->next = hashTable[ii];
    hashTable[ii] = nn;

    /* entry not found, and therefore added. return false */
    return 0;
}



/* Add a directory name to the file name */

char* addDirectoryName(const char* directoryName, const char* fileName)
{
    char* pathName;
    pathName = (char*)malloc(strlen(directoryName) + strlen(fileName) + 2);

    strcpy(pathName, directoryName);

    if (directoryName[strlen(directoryName)-1] != '/')
    {
        strcat(pathName, "/");
    }

    strcat(pathName, fileName);

    return pathName;
}


/* open a file and create buffer and put on stack stack */

void nextFile(const char* fileName)
{
    int d;
    char* pathName;

    if (lookUp(fileHashTable, fileName)) return;

    if(currentBuffer >= FILE_STACK_SIZE)
    {
        fprintf
        (
            stderr,
            "depth of file search exceeds stack size %d "
            "while opening %s for file %s\n",
            FILE_STACK_SIZE, fileName, sourceFile
        );
        exit(1);
    }

    buffers[currentBuffer++] = YY_CURRENT_BUFFER;

    if(!(yyin = fopen(fileName, "r")))
    {
        for(d=0; d<nDirectories; d++)
        {
            pathName = addDirectoryName(directories[d], fileName);

            if ((yyin = fopen(pathName, "r")))
            { 
                printf("%s: %s\n", depFile, pathName);
                yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
                BEGIN(INITIAL);

                free(pathName);

                return;
            }

            free(pathName);
        }
        fprintf
        (
            stderr, 
            "could not open file %s for source file %s\n", 
            fileName, sourceFile
        );

        fflush(stdout);
        currentBuffer--;
        BEGIN(INITIAL);
    }
    else
    {
        printf("%s: %s\n", depFile, fileName);
        fflush(stdout);

        yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
        BEGIN(INITIAL);
    }
}


void dotToSlash(char* fileName)
{
    int i, len;

    len = strlen(fileName);

    for (i=0; i<len; i++)
    {
        if (fileName[i] == '.') fileName[i] = '/';
    }
}


void importFile(const char* fileName)
{
    char* javaFileName;
    int fileNameLen;

    fileNameLen = strlen(fileName);
    javaFileName = (char*)malloc(fileNameLen + 6);
    javaFileName[0] = 0;
    strncat(javaFileName, fileName, fileNameLen - 1);
    dotToSlash(javaFileName);
    strcat(javaFileName, ".java");

    nextFile(javaFileName);

    free(javaFileName);
}


void importDirectory(const char* dirName)
{
    int dirNameLen;
    char *uDirName, *path;
    DIR *source;
    struct dirent *list;

    if (lookUp(dirHashTable, dirName)) return;

    dirNameLen = strlen(dirName);
    uDirName = strdup(dirName);
    dotToSlash(uDirName);
    uDirName[dirNameLen-2] = 0;

    if ((source = opendir(uDirName)) == NULL)
    {
        fprintf
        (
            stderr, 
            "could not open directory %s\n", 
            uDirName
        );
        free(uDirName);

        return;
    }
    else
    {
        /* Read and parse all the entries in the directory */
        while ((list = readdir(source)) != NULL)
        {
            if
            (
                strstr(list->d_name, ".java")
             && !strstr(list->d_name, ".java~")
            )
            {
                path = addDirectoryName(uDirName, list->d_name);
                nextFile(path);
                free(path);
            }
        }

        closedir(source);
        free(uDirName);
    }
}


/* the lexer calls yywrap to handle EOF conditions */

int yywrap()
{
    /* Delete buffer which has just reached EOF */
    yy_delete_buffer(YY_CURRENT_BUFFER);

    /* Set buffer counter to previous buffer */
    currentBuffer--;

    if (currentBuffer >= 0) /* if buffer counter refers to a valid file */
    {
        /* reset input buffer to the previous buffer on the stack */
        //yyin = buffers[currentBuffer];
        yy_switch_to_buffer(buffers[currentBuffer]);

        /* Return to the normal state for the previous buffer on the stack */
        BEGIN(INITIAL);

        /* return 0 to inform lex to continue reading */
        return 0;
    }
    else                 /* else there are no more buffers on the stack */
    {
        /* return 1 to inform lex finish now that all buffers have been read */
        return 1;
    }
}


/*****************************************************************************/
