/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /home/daffy/u0/vern/flex/RCS/flex.skl,v 2.91 96/09/10 16:58:48 vern Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 19
#define YY_END_OF_BUFFER 20
static yyconst short int yy_accept[285] =
    {   0,
        0,    0,    0,    0,    6,    6,    0,    0,    0,    0,
       17,   17,   20,   18,   18,   18,   18,   18,   18,   18,
       18,    3,    3,    3,    3,    3,    3,    3,    3,    3,
        6,    6,    6,    6,    6,    6,   18,   18,   18,   18,
       18,   14,   18,   18,   18,   18,   18,   18,   18,   18,
       18,   17,   17,   17,   17,   17,   17,   17,   17,    0,
        2,    0,    0,    0,    0,    0,    0,    0,    0,    4,
        6,    2,    6,    6,    6,    6,    6,    6,    6,    0,
        0,   14,    0,    0,   15,    2,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,   17,

       17,    2,   17,   17,   17,   17,   17,   17,   17,   17,
        0,    0,    1,    0,    0,    0,    6,    6,    6,    0,
        0,    0,   14,    0,    0,    0,    0,    0,    0,    0,
        0,   17,   17,    1,   17,   17,   17,    0,    0,    0,
        0,    6,    6,    0,    0,   15,    0,    0,    0,   10,
        0,    0,    0,    0,    0,    9,    0,    0,    0,   12,
        0,    0,    0,    0,   17,   17,   17,   17,    0,    0,
        0,    0,    6,    6,    0,   10,    0,   10,    0,    0,
        0,    8,    0,    9,    0,    9,   12,    0,   12,    0,
        0,    0,   11,    0,    0,    0,   17,   17,   17,   17,

        0,    0,    0,    0,    6,    6,    0,   10,    8,    0,
        8,    0,    9,   12,   11,    0,   11,    0,    0,    0,
       17,   17,   17,   17,    0,    0,    0,    7,    6,    6,
        0,    8,    0,   11,    0,    0,    7,   17,   17,   17,
        7,    0,    0,    6,    0,    0,    0,   17,   17,    0,
        0,    6,    0,    0,    0,    0,   13,    0,   17,   17,
        0,    5,    0,   13,    0,   13,   17,    5,    0,    0,
       13,   17,    0,    0,   17,    0,    0,   17,    0,    0,
       17,   16,   16,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    1,    5,    6,    1,    1,    1,    7,    1,
        1,    8,    1,    1,    1,    1,    9,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,   10,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,   11,    1,   12,   13,

       14,    1,   15,   16,   17,   18,    1,   19,   20,   21,
       22,   23,    1,   24,   25,   26,   27,   28,   29,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[30] =
    {   0,
        1,    1,    2,    3,    4,    1,    5,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1
    } ;

static yyconst short int yy_base[316] =
    {   0,
        0,    8,   11,   24,   40,   48,   14,   64,   81,   54,
       20,  109,  806,  807,  807,  801,   26,   57,  115,    4,
      781,  807,  807,  792,  782,   28,  118,  121,   60,  766,
        0,    0,   30,  127,  126,  761,   38,   59,   68,  104,
      131,  126,  137,  138,  142,  146,  147,  173,  772,  156,
      156,    0,    0,  767,   71,  161,  178,  183,  746,  757,
      807,  753,  187,  184,  731,  190,  195,  725,  718,  807,
        0,    0,  205,  209,  201,  716,  212,  710,  703,  161,
      209,  212,  217,  713,  708,  220,  228,  224,  227,  231,
      232,  235,    0,  244,  243,  680,  258,  244,  249,    0,

      678,    0,    0,  264,  265,  659,  272,  269,  656,  651,
      669,  669,  807,  281,  637,  626,  287,  630,  614,  289,
      297,  298,  306,  305,  269,  309,  313,  317,  627,  316,
      321,  614,  165,    0,  330,  596,  577,  594,  331,  576,
      568,  567,  558,  334,  346,  347,  348,  566,  352,  356,
      360,  359,  367,  562,  368,  374,  375,  556,  381,  382,
      388,  539,  387,  391,  538,  401,  515,  509,  499,  406,
      469,  463,  449,  442,  409,  450,  406,  416,  417,  446,
      423,  424,  427,  442,  431,  437,  438,  441,  445,  449,
      420,  453,  457,  416,  456,  286,  405,  467,  377,  368,

      371,  468,  368,  337,  361,  398,  469,  470,  353,  482,
      483,  430,  489,  490,  349,  496,  497,  328,  500,  507,
      323,  510,  307,  516,  283,  203,  281,  517,  274,  520,
      515,  521,  520,  527,  530,  531,  544,  263,  461,  235,
      545,  194,  551,  554,  549,  555,  560,  190,  565,  179,
      569,  573,  571,  575,  151,  579,  583,  592,  132,  599,
      115,  807,  597,  127,  601,  605,   48,    0,   42,  604,
      611,   34,   26,  612,   17,  621,  625,  626,  630,  636,
      643,  807,  631,  807,  650,  655,  660,  665,  670,  675,
      680,  685,  689,  694,  699,  704,  709,  714,  719,  724,

      729,  734,  739,  744,  749,  754,  759,  764,  769,  774,
      779,  784,  789,  794,  799
    } ;

static yyconst short int yy_def[316] =
    {   0,
      285,  285,  286,  286,  287,  287,  285,  285,  284,    9,
      288,  288,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      289,  289,  289,  289,  289,  289,  290,  290,  290,  291,
      290,  290,  290,  290,  290,  290,  290,  290,   48,   48,
      290,  292,  292,  292,  292,  292,  292,  292,  292,  284,
      284,  293,  284,  284,  284,  284,  284,  284,  284,  284,
      289,  289,  294,  289,  289,  289,  289,  289,  289,  290,
      291,  290,  290,  291,  291,  291,  295,  290,  290,  290,
      290,  290,   48,   48,  290,   48,   48,  290,  290,  292,

      292,  292,  296,  292,  292,  292,  292,  292,  292,  292,
      284,  293,  284,  284,  284,  284,  294,  289,  289,  290,
      295,  297,  295,  298,  290,  290,  299,  300,   48,  290,
      290,  292,  296,  292,  292,  292,  292,  284,  284,  284,
      284,  289,  289,  290,  297,  297,  298,  301,  302,  298,
      303,  290,  299,  304,  305,  299,  300,  306,  307,  300,
      308,   48,  290,  290,  292,  292,  292,  292,  284,  284,
      284,  284,  289,  289,  290,  301,  302,  302,  303,  309,
      310,  303,  290,  304,  305,  305,  306,  307,  307,  308,
      311,  312,  308,   48,  290,  290,  292,  292,  292,  292,

      284,  284,  284,  284,  289,  289,  290,  302,  309,  310,
      310,  290,  305,  307,  311,  312,  312,   48,  290,  290,
      292,  292,  292,  292,  284,  284,  284,  284,  289,  289,
      290,  310,  290,  312,  290,  290,  290,  292,  292,  292,
      292,  284,  284,  289,  290,  313,  290,  292,  292,  284,
      284,  289,  290,  313,  314,  315,  313,  290,  292,  292,
      284,  284,  290,  314,  315,  315,  292,  292,  284,  290,
      315,  292,  284,  290,  292,  284,  290,  292,  284,  290,
      292,  284,  290,    0,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,

      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284
    } ;

static yyconst short int yy_nxt[837] =
    {   0,
      284,   15,  134,   16,  284,   67,  112,   67,   17,   18,
      284,   19,   23,   20,   24,   15,   17,   16,   25,   26,
       68,   53,   17,   54,   21,   27,   14,   28,   55,   29,
      278,   25,   26,   61,   62,   61,   62,   72,   73,  276,
       30,   32,   14,   16,   14,   81,  275,   82,   33,   34,
       14,   19,   14,   35,  273,   48,   33,   49,   63,   50,
       63,   67,   64,   67,   36,   18,   81,   19,   82,   20,
       51,   83,   17,   65,  272,   81,   68,   82,  102,  103,
       21,   37,   38,   14,   39,   14,   37,   37,   40,   41,
       42,   37,   43,   37,   37,   37,   37,   37,   44,   45,

       37,   37,   46,   37,   37,   47,   37,   37,   37,   37,
       56,   81,   57,   85,   58,   14,   63,   55,   66,   63,
       64,   63,   63,   64,   66,   59,   64,   77,   74,   67,
       63,   65,   75,   81,   65,   82,  264,   65,   86,   87,
       82,  269,   78,   76,   81,   81,   82,   82,   89,   81,
      267,   82,   90,   81,   81,   82,   82,   97,   88,   97,
      264,   80,  104,   81,  104,   82,  105,  134,   81,   91,
       82,  112,   98,   92,   93,   99,   93,  106,   94,  104,
       81,  107,   82,  105,  108,   67,  108,   67,   63,   95,
       63,   63,   64,  114,  106,   64,   67,  261,   67,  109,

       68,  259,   77,   65,   67,  250,   65,  113,  112,  112,
       74,   68,   63,   77,   75,   67,   81,   78,   85,   81,
      120,   82,   69,  242,   81,   76,   82,   81,   78,   85,
      113,   81,  112,   82,   81,  122,   82,  123,   81,   81,
       82,   82,   81,  124,   82,   97,  127,   97,  249,   80,
       81,   81,   82,   82,  125,  128,   81,  126,   82,   97,
       98,   97,   99,   80,  130,  104,  108,  104,  108,  105,
      108,  131,  108,  104,   98,  135,   81,  105,   82,  151,
      106,  109,   63,  248,  139,  109,   64,  244,  106,  113,
      112,  112,  144,   81,  243,   82,   81,   65,   82,  113,

      113,  112,  112,  242,  122,  122,  123,  146,  113,  148,
      112,  220,  149,  122,  150,  123,   81,  154,   82,  240,
      155,  158,  156,   81,  159,   82,  160,  163,   81,  152,
       82,  104,   63,  166,  170,  105,   64,  175,  228,  238,
      228,   81,  164,   82,  235,  161,  106,   65,  113,  113,
      112,  112,  148,  122,  122,  149,  148,  150,  215,  149,
      148,  178,  209,  149,  180,  150,   81,  181,   82,  182,
      183,  154,  154,  229,  155,  155,  156,  186,  154,  158,
      227,  155,  159,  156,  160,  158,  158,  225,  159,  159,
      189,  160,  191,  224,   81,  192,   82,  193,   81,  230,

       82,  228,  104,  223,  198,  195,  105,   63,  221,  202,
      148,   64,  207,  149,  196,  208,   81,  106,   82,  218,
      148,  180,   65,  149,  181,  208,  182,  180,  180,  215,
      181,  181,  211,  182,   81,  154,   82,   81,  155,   82,
      213,  154,  212,  233,  155,  158,  213,  187,  159,  158,
      214,  184,  159,  191,  214,  209,  192,  191,  193,  176,
      192,  191,  217,   81,  192,   82,  193,  206,  104,   63,
      222,   63,  105,   64,  148,  205,   81,  149,   82,  208,
      110,  248,  219,  106,  226,  231,  180,  180,  204,  181,
      181,  232,  232,  154,  158,  203,  155,  159,  213,  214,

      191,  191,  201,  192,  192,  234,  234,   81,  237,   82,
      237,  104,  236,  104,   81,  105,   82,  241,  228,  241,
      228,  230,   81,  228,   82,  180,  239,   81,  181,   82,
      232,  191,  200,  199,  192,  245,  234,   81,   81,   82,
       82,  197,  194,  246,  247,  237,  241,  237,  241,   99,
      245,   81,  251,   82,  251,  252,   81,  251,   82,  255,
      253,  258,  256,  258,  257,  187,  260,   81,  260,   82,
      251,  184,  251,  262,  252,  176,  251,  262,   81,  255,
       82,  174,  256,  255,  257,  173,  256,  255,  266,  263,
      256,  172,  257,  258,  171,  258,  262,  169,  168,   81,

      260,   82,  260,  268,   81,  255,   82,  167,  256,  255,
      271,   81,  256,   82,  271,  255,  274,  165,  256,   81,
      271,   82,  279,  270,  279,  277,  280,  281,  280,  281,
      162,  279,   81,  279,   82,  143,  282,  280,   81,  280,
       82,  142,  283,   81,  281,   82,  281,  141,  140,  282,
       14,   14,   14,   14,   14,   22,   22,   22,   22,   22,
       31,   31,   31,   31,   31,   52,   52,   52,   52,   52,
       71,  113,  138,  137,   71,   80,  136,   80,  110,   80,
       84,  132,   84,  129,   84,  100,  100,  100,  100,  112,
      112,  112,  112,  112,  117,  117,  117,  117,  117,  121,

      121,  121,  121,  121,  133,  133,  133,  133,  133,  145,
      145,  145,  145,  145,  147,   81,  147,  147,  147,  153,
       81,  153,  153,  153,  157,  119,  157,  157,  157,  148,
      118,  148,  148,  148,  177,   79,  177,  177,  177,  179,
      116,  179,  179,  179,  154,  115,  154,  154,  154,  185,
       69,  185,  185,  185,  158,  113,  158,  158,  158,  188,
      111,  188,  188,  188,  190,  110,  190,  190,  190,  180,
      101,  180,  180,  180,  210,   96,  210,  210,  210,  191,
       79,  191,  191,  191,  216,   69,  216,  216,  216,  254,
       70,  254,  254,  254,  255,   60,  255,  255,  255,  265,

       69,  265,  265,  265,   60,  284,   13,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284
    } ;

static yyconst short int yy_chk[837] =
    {   0,
        0,    1,  103,    1,    0,   20,  103,   20,    1,    2,
        0,    2,    3,    2,    3,    7,    2,    7,    3,    3,
       20,   11,    7,   11,    2,    4,   11,    4,   11,    4,
      275,    4,    4,   17,   17,   26,   26,   33,   33,  273,
        4,    5,    5,    5,    5,   37,  272,   37,    5,    6,
        6,    6,    6,    6,  269,   10,    6,   10,   18,   10,
       18,   29,   18,   29,    6,    8,   38,    8,   38,    8,
       10,   39,    8,   18,  267,   39,   29,   39,   55,   55,
        8,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,

        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
       12,   40,   12,   40,   12,   12,   19,   12,   19,   27,
       19,   27,   28,   27,   28,   12,   28,   35,   34,   35,
       34,   19,   34,   42,   27,   42,  264,   28,   41,   41,
       41,  261,   35,   34,   43,   44,   43,   44,   44,   45,
      259,   45,   45,   46,   47,   46,   47,   50,   43,   50,
      255,   50,   56,   51,   56,   51,   56,  133,   80,   46,
       80,  133,   50,   47,   48,   51,   48,   56,   48,   57,
       48,   57,   48,   57,   58,   64,   58,   64,   63,   48,
       63,   66,   63,   66,   57,   66,   67,  250,   67,   58,

       64,  248,   75,   63,   75,  242,   66,   73,   73,   73,
       74,   67,   74,   77,   74,   77,   81,   75,   81,   82,
       83,   82,  226,  226,   83,   74,   83,   86,   77,   86,
       87,   88,   87,   88,   89,   87,   89,   87,   90,   91,
       90,   91,   92,   88,   92,   94,   91,   94,  240,   94,
       95,   98,   95,   98,   89,   92,   99,   90,   99,   97,
       94,   97,   95,   97,   98,  104,  105,  104,  105,  104,
      108,   99,  108,  107,   97,  107,  125,  107,  125,  125,
      104,  105,  114,  238,  114,  108,  114,  229,  107,  117,
      117,  117,  120,  196,  227,  196,  120,  114,  120,  121,

      122,  121,  122,  225,  121,  122,  121,  122,  123,  124,
      123,  196,  124,  123,  124,  123,  126,  127,  126,  223,
      127,  128,  127,  130,  128,  130,  128,  130,  131,  126,
      131,  135,  139,  135,  139,  135,  139,  144,  204,  221,
      204,  144,  131,  144,  218,  128,  135,  139,  145,  146,
      145,  146,  147,  145,  146,  147,  149,  147,  215,  149,
      150,  149,  209,  150,  151,  150,  152,  151,  152,  151,
      152,  153,  155,  205,  153,  155,  153,  155,  156,  157,
      203,  156,  157,  156,  157,  159,  160,  201,  159,  160,
      159,  160,  161,  200,  163,  161,  163,  161,  164,  206,

      164,  206,  166,  199,  166,  163,  166,  170,  197,  170,
      177,  170,  175,  177,  164,  177,  175,  166,  175,  194,
      178,  179,  170,  178,  179,  178,  179,  181,  182,  191,
      181,  182,  181,  182,  183,  185,  183,  212,  185,  212,
      185,  186,  183,  212,  186,  188,  186,  187,  188,  189,
      188,  184,  189,  190,  189,  180,  190,  192,  190,  176,
      192,  193,  192,  195,  193,  195,  193,  174,  198,  202,
      198,  202,  198,  202,  208,  173,  207,  208,  207,  208,
      239,  239,  195,  198,  202,  207,  210,  211,  172,  210,
      211,  210,  211,  213,  214,  171,  213,  214,  213,  214,

      216,  217,  169,  216,  217,  216,  217,  219,  220,  219,
      220,  222,  219,  222,  220,  222,  220,  224,  228,  224,
      228,  230,  231,  230,  231,  232,  222,  233,  232,  233,
      232,  234,  168,  167,  234,  231,  234,  235,  236,  235,
      236,  165,  162,  233,  236,  237,  241,  237,  241,  235,
      235,  237,  243,  237,  243,  244,  245,  244,  245,  246,
      245,  247,  246,  247,  246,  158,  249,  247,  249,  247,
      251,  154,  251,  251,  252,  148,  252,  252,  253,  254,
      253,  143,  254,  256,  254,  142,  256,  257,  256,  253,
      257,  141,  257,  258,  140,  258,  258,  138,  137,  258,

      260,  258,  260,  260,  263,  265,  263,  136,  265,  266,
      265,  270,  266,  270,  266,  271,  270,  132,  271,  274,
      271,  274,  276,  263,  276,  274,  277,  278,  277,  278,
      129,  279,  277,  279,  277,  119,  279,  280,  283,  280,
      283,  118,  280,  280,  281,  280,  281,  116,  115,  281,
      285,  285,  285,  285,  285,  286,  286,  286,  286,  286,
      287,  287,  287,  287,  287,  288,  288,  288,  288,  288,
      289,  112,  111,  110,  289,  290,  109,  290,  106,  290,
      291,  101,  291,   96,  291,  292,  292,  292,  292,  293,
      293,  293,  293,  293,  294,  294,  294,  294,  294,  295,

      295,  295,  295,  295,  296,  296,  296,  296,  296,  297,
      297,  297,  297,  297,  298,   85,  298,  298,  298,  299,
       84,  299,  299,  299,  300,   79,  300,  300,  300,  301,
       78,  301,  301,  301,  302,   76,  302,  302,  302,  303,
       69,  303,  303,  303,  304,   68,  304,  304,  304,  305,
       65,  305,  305,  305,  306,   62,  306,  306,  306,  307,
       60,  307,  307,  307,  308,   59,  308,  308,  308,  309,
       54,  309,  309,  309,  310,   49,  310,  310,  310,  311,
       36,  311,  311,  311,  312,   30,  312,  312,  312,  313,
       25,  313,  313,  313,  314,   24,  314,  314,  314,  315,

       21,  315,  315,  315,   16,   13,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284,  284,  284,  284,  284,
      284,  284,  284,  284,  284,  284
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "wmkdep.l"
#define INITIAL 0
#line 2 "wmkdep.l"
/*----------------------------------------------------------------------------*\
 =========                   |
 \\      /   F ield          | OpenFOAM: The Open Source CFD Toolbox
  \\    /    O peration      |
   \\  /     A nd            | Copyright (C) 1991-2007 OpenCFD Ltd.
    \\/      M anipulation   |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

Application
    wmkdep

Description
     A fast dependency list generator which emulates the behaviour and
     output of cpp -M. However, the output contains no duplications and 
     is ~40% faster than cpp.

     The algorithm uses flex to scan for includes and searches the files
     found.  Each file is entererd into a hash table so that files are
     scaned only once.  This is why this program is faster than cpp.

Usage
    wmkdep [ -Idirectory ... -Idirectory] filename

\*----------------------------------------------------------------------------*/

#define FILE_STACK_SIZE 300
#define HASH_TABLE_SIZE 500

#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <dirent.h>

void nextFile(const char* fileName);
void importFile(const char* fileName);
void importDirectory(const char* dirName);

#   undef yywrap	/* sometimes a macro by default */

#define CMNT 1
#define CFNAME 2
#define SCFNAME 3
#define JFNAME 4
#define FFNAME 5

#line 707 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	if ( yyleng > 0 ) \
		yy_current_buffer->yy_at_bol = \
				(yytext[yyleng - 1] == '\n'); \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 60 "wmkdep.l"


#line 864 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
		yy_current_state += YY_AT_BOL();
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 285 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 807 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 62 "wmkdep.l"
;               /* remove c++ style one line comments */
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 64 "wmkdep.l"
BEGIN(CMNT);    /* start removing c style comment */
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 65 "wmkdep.l"
;
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 66 "wmkdep.l"
BEGIN(INITIAL); /* end removing c style comment */
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 68 "wmkdep.l"
BEGIN(CFNAME);  /* c-file name */
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 69 "wmkdep.l"
{ BEGIN(INITIAL); nextFile(yytext); } /*"*/
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 71 "wmkdep.l"
BEGIN(JFNAME);  /* java-file name */
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 72 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 73 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 74 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 75 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 76 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 77 "wmkdep.l"
BEGIN(INITIAL);
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 78 "wmkdep.l"
{ BEGIN(INITIAL); importFile(yytext); } /*"*/
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 79 "wmkdep.l"
{ BEGIN(INITIAL); importDirectory(yytext); } /*"*/
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 81 "wmkdep.l"
BEGIN(FFNAME);  /* FORTRAN-file name */
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 82 "wmkdep.l"
{ BEGIN(INITIAL); nextFile(yytext); } /*'*/
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 84 "wmkdep.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 86 "wmkdep.l"
ECHO;
	YY_BREAK
#line 1043 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(CMNT):
case YY_STATE_EOF(CFNAME):
case YY_STATE_EOF(SCFNAME):
case YY_STATE_EOF(JFNAME):
case YY_STATE_EOF(FFNAME):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;
	yy_current_state += YY_AT_BOL();

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 285 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 285 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 284);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;

	yy_current_buffer->yy_at_bol = (c == '\n');

	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 86 "wmkdep.l"



int nDirectories;
char** directories;
char* sourceFile = NULL;
char* sourceExt = NULL;
char* objectFile = NULL;
char* classFile = NULL;
char* depFile = NULL;

int main(int argc, char* argv[])
{
    char *dotPtr, *slashPtr;
    int i;

    if (argc == 1)
    {
        fprintf(stderr,"input file not supplied\n");
        exit(1);
    }

    sourceFile = (char*)malloc(strlen(argv[argc-1]) + 1);
    strcpy(sourceFile, argv[argc-1]);
    fprintf(stderr,"Making dependency list for source file %s\n", sourceFile);
    
    
    /* Get list of -I directories. */
    nDirectories = 0;

    for (i = 1; i < argc; i++)
    {
        if (strncmp(argv[i], "-I", 2) == 0)
        {
            nDirectories++;
        }
    }

    directories = (char**)malloc(sizeof(char*)*nDirectories);

    nDirectories = 0;

    for (i = 1; i < argc; i++)
    {
        if (strncmp(argv[i], "-I", 2) == 0)
        {
            directories[nDirectories++] = strdup(argv[i] + 2);
        }
    }



    if ((dotPtr = strrchr(sourceFile, '.')) == NULL)
    {
        fprintf
        (
            stderr,
            "Cannot find extension in source file name %s\n",
            sourceFile
        );
        exit(1);
    }

    if ((slashPtr = strrchr(sourceFile, '/')) == NULL)
    {
        slashPtr = sourceFile;
    }
    else
    {
        slashPtr++;
    }

    sourceExt = (char*)malloc(strlen(sourceFile));
    sourceExt[0] = 0;
    strncat
    (
        sourceExt,
        dotPtr+1,
        (&sourceFile[strlen(sourceFile) - 1] - dotPtr)/sizeof(char)
    );

    /* initialise depFile to zero and use strncat rather than strncpy
       because there is a bug in the SGI strncat that if 0 preceeds the .
       it inserts a space */
    depFile = (char*)malloc(strlen(sourceFile) + 3);
    depFile[0] = 0;
    strncat(depFile, sourceFile, (dotPtr - sourceFile)/sizeof(char));
    strcat(depFile, ".dep");

    if (strcmp(sourceExt, "java") == 0)
    {
        classFile = (char*)malloc(strlen(sourceFile) + 17);
        strcpy(classFile, "$(CLASSES_DIR)/");
        strncat(classFile, sourceFile, (dotPtr - sourceFile)/sizeof(char));
        strcat(classFile, ".class");

        printf("%s: %s\n", classFile, depFile);
    }
    else
    {
        objectFile = (char*)malloc(strlen(sourceFile) + 16);
        strcpy(objectFile, "$(OBJECTS_DIR)/");
        strncat(objectFile, slashPtr, (dotPtr - slashPtr)/sizeof(char));
        strcat(objectFile, ".o");

        printf("%s: %s\n", objectFile, depFile);
    }

    nextFile(sourceFile);
    yylex();


    for (i = 0; i < nDirectories; i++)
    {
        free(directories[i]);
    }
    free(directories);

    free(sourceFile);
    free(sourceExt);
    free(objectFile);
    free(classFile);
    free(depFile);

    return 0;
}


int currentBuffer = 0;                     /* Buffer pointer stack counter */
YY_BUFFER_STATE buffers[FILE_STACK_SIZE];  /* Buffer pointer stack */

/* file name entry in hash table */

struct FileName
{
    char* name;
    struct FileName* next;
};

struct FileName* fileHashTable[HASH_TABLE_SIZE];   /* File hash table */
struct FileName* dirHashTable[HASH_TABLE_SIZE];    /* Directory hash table */


/* lookup name in hash table, if not found insert in table */

int lookUp(struct FileName** hashTable, const char* p)
{
    int ii = 0;
    struct FileName* n;
    struct FileName* nn;

    /* hash */
    const char* pp = p;
    while (*pp) ii = ii<<1 ^ *pp++;
    if (ii < 0) ii = -ii;
    ii %= HASH_TABLE_SIZE;

    /* search */
    for (n=hashTable[ii]; n; n=n->next)
    {
        if (strcmp(p, n->name) == 0)
        {
            /* entry found so return true */
            return 1;
        }
    }

    /* insert */
    nn = (struct FileName*)malloc(sizeof(struct FileName));
    nn->name = (char*)malloc(strlen(p)+1);
    strcpy(nn->name, p);
    nn->next = hashTable[ii];
    hashTable[ii] = nn;

    /* entry not found, and therefore added. return false */
    return 0;
}



/* Add a directory name to the file name */

char* addDirectoryName(const char* directoryName, const char* fileName)
{
    char* pathName;
    pathName = (char*)malloc(strlen(directoryName) + strlen(fileName) + 2);

    strcpy(pathName, directoryName);

    if (directoryName[strlen(directoryName)-1] != '/')
    {
        strcat(pathName, "/");
    }

    strcat(pathName, fileName);

    return pathName;
}


/* open a file and create buffer and put on stack stack */

void nextFile(const char* fileName)
{
    int d;
    char* pathName;

    if (lookUp(fileHashTable, fileName)) return;

    if(currentBuffer >= FILE_STACK_SIZE)
    {
        fprintf
        (
            stderr,
            "depth of file search exceeds stack size %d "
            "while opening %s for file %s\n",
            FILE_STACK_SIZE, fileName, sourceFile
        );
        exit(1);
    }

    buffers[currentBuffer++] = YY_CURRENT_BUFFER;

    if(!(yyin = fopen(fileName, "r")))
    {
        for(d=0; d<nDirectories; d++)
        {
            pathName = addDirectoryName(directories[d], fileName);

            if ((yyin = fopen(pathName, "r")))
            { 
                printf("%s: %s\n", depFile, pathName);
                yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
                BEGIN(INITIAL);

                free(pathName);

                return;
            }

            free(pathName);
        }
        fprintf
        (
            stderr, 
            "could not open file %s for source file %s\n", 
            fileName, sourceFile
        );

        fflush(stdout);
        currentBuffer--;
        BEGIN(INITIAL);
    }
    else
    {
        printf("%s: %s\n", depFile, fileName);
        fflush(stdout);

        yy_switch_to_buffer(yy_create_buffer(yyin, YY_BUF_SIZE));
        BEGIN(INITIAL);
    }
}


void dotToSlash(char* fileName)
{
    int i, len;

    len = strlen(fileName);

    for (i=0; i<len; i++)
    {
        if (fileName[i] == '.') fileName[i] = '/';
    }
}


void importFile(const char* fileName)
{
    char* javaFileName;
    int fileNameLen;

    fileNameLen = strlen(fileName);
    javaFileName = (char*)malloc(fileNameLen + 6);
    javaFileName[0] = 0;
    strncat(javaFileName, fileName, fileNameLen - 1);
    dotToSlash(javaFileName);
    strcat(javaFileName, ".java");

    nextFile(javaFileName);

    free(javaFileName);
}


void importDirectory(const char* dirName)
{
    int dirNameLen;
    char *uDirName, *path;
    DIR *source;
    struct dirent *list;

    if (lookUp(dirHashTable, dirName)) return;

    dirNameLen = strlen(dirName);
    uDirName = strdup(dirName);
    dotToSlash(uDirName);
    uDirName[dirNameLen-2] = 0;

    if ((source = opendir(uDirName)) == NULL)
    {
        fprintf
        (
            stderr, 
            "could not open directory %s\n", 
            uDirName
        );
        free(uDirName);

        return;
    }
    else
    {
        /* Read and parse all the entries in the directory */
        while ((list = readdir(source)) != NULL)
        {
            if
            (
                strstr(list->d_name, ".java")
             && !strstr(list->d_name, ".java~")
            )
            {
                path = addDirectoryName(uDirName, list->d_name);
                nextFile(path);
                free(path);
            }
        }

        closedir(source);
        free(uDirName);
    }
}


/* the lexer calls yywrap to handle EOF conditions */

int yywrap()
{
    /* Delete buffer which has just reached EOF */
    yy_delete_buffer(YY_CURRENT_BUFFER);

    /* Set buffer counter to previous buffer */
    currentBuffer--;

    if (currentBuffer >= 0) /* if buffer counter refers to a valid file */
    {
        /* reset input buffer to the previous buffer on the stack */
        //yyin = buffers[currentBuffer];
        yy_switch_to_buffer(buffers[currentBuffer]);

        /* Return to the normal state for the previous buffer on the stack */
        BEGIN(INITIAL);

        /* return 0 to inform lex to continue reading */
        return 0;
    }
    else                 /* else there are no more buffers on the stack */
    {
        /* return 1 to inform lex finish now that all buffers have been read */
        return 1;
    }
}


/*****************************************************************************/
