package FoamXServer;


/**
* FoamXServer/ApplicationClassDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// Application class descriptor structure.
public final class ApplicationClassDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public String category = null;
  public boolean systemClass = false;

  public ApplicationClassDescriptor ()
  {
  } // ctor

  public ApplicationClassDescriptor (String _name, String _category, boolean _systemClass)
  {
    name = _name;
    category = _category;
    systemClass = _systemClass;
  } // ctor

} // class ApplicationClassDescriptor
