package FoamXServer;

/**
* FoamXServer/ApplicationDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 22 June 2005 14:41:58 o'clock BST
*/


// Application descriptor structure.
public final class ApplicationDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.ApplicationDescriptor value = null;

  public ApplicationDescriptorHolder ()
  {
  }

  public ApplicationDescriptorHolder (FoamXServer.ApplicationDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.ApplicationDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.ApplicationDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.ApplicationDescriptorHelper.type ();
  }

}
