package FoamXServer;


/**
* FoamXServer/floatListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* Wednesday, February 12, 2003 11:34:29 AM GMT
*/

public final class floatListHolder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public floatListHolder ()
  {
  }

  public floatListHolder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.floatListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.floatListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.floatListHelper.type ();
  }

}
