package FoamXServer;

/**
* FoamXServer/FoamXAnyHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// -------------------------------------------------------------------------
public final class FoamXAnyHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.FoamXAny value = null;

  public FoamXAnyHolder ()
  {
  }

  public FoamXAnyHolder (FoamXServer.FoamXAny initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.FoamXAnyHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.FoamXAnyHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.FoamXAnyHelper.type ();
  }

}
