package FoamXServer;


/**
* FoamXServer/HostDescriptor.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 22 June 2005 14:41:58 o'clock BST
*/


// Host descriptor structure.
public final class HostDescriptor implements org.omg.CORBA.portable.IDLEntity
{
  public String name = null;
  public boolean alive = false;

  public HostDescriptor ()
  {
  } // ctor

  public HostDescriptor (String _name, boolean _alive)
  {
    name = _name;
    alive = _alive;
  } // ctor

} // class HostDescriptor
