package FoamXServer;

/**
* FoamXServer/HostDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// Host descriptor structure.
public final class HostDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.HostDescriptor value = null;

  public HostDescriptorHolder ()
  {
  }

  public HostDescriptorHolder (FoamXServer.HostDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.HostDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.HostDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.HostDescriptorHelper.type ();
  }

}
