package FoamXServer;


/**
* FoamXServer/IDictionaryEntry.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// -------------------------------------------------------------------------
public interface IDictionaryEntry extends IDictionaryEntryOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IDictionaryEntry
