package FoamXServer;


/**
* FoamXServer/longListHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* Wednesday, February 12, 2003 11:34:29 AM GMT
*/

public final class longListHolder implements org.omg.CORBA.portable.Streamable
{
  public int value[] = null;

  public longListHolder ()
  {
  }

  public longListHolder (int[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.longListHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.longListHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.longListHelper.type ();
  }

}
