package FoamXServer;


/**
* FoamXServer/point3Holder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* Wednesday, February 12, 2003 11:34:29 AM GMT
*/

public final class point3Holder implements org.omg.CORBA.portable.Streamable
{
  public float value[] = null;

  public point3Holder ()
  {
  }

  public point3Holder (float[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.point3Helper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.point3Helper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.point3Helper.type ();
  }

}
