package FoamXServer;

/**
* FoamXServer/TimeSelectionHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* Thursday, March 13, 2003 4:23:04 PM GMT
*/

public final class TimeSelectionHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.TimeSelection value = null;

  public TimeSelectionHolder ()
  {
  }

  public TimeSelectionHolder (FoamXServer.TimeSelection initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.TimeSelectionHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.TimeSelectionHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.TimeSelectionHelper.type ();
  }

}
