package FoamXServer;


/**
* FoamXServer/TimeSelectionHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* Thursday, March 13, 2003 4:23:04 PM GMT
*/

abstract public class TimeSelectionHelper
{
  private static String  _id = "IDL:FoamXServer/TimeSelection:1.0";

  public static void insert (org.omg.CORBA.Any a, FoamXServer.TimeSelection that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static FoamXServer.TimeSelection extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_enum_tc (FoamXServer.TimeSelectionHelper.id (), "TimeSelection", new String[] { "TIME_LATESTTIME", "TIME_FIRSTTIME", "TIME_NOTIME", "TIME_ALLTIMES"} );
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static FoamXServer.TimeSelection read (org.omg.CORBA.portable.InputStream istream)
  {
    return FoamXServer.TimeSelection.from_int (istream.read_long ());
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, FoamXServer.TimeSelection value)
  {
    ostream.write_long (value.value ());
  }

}
