package FoamXServer;

/**
* FoamXServer/UtilityDescriptorHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from FoamX.idl
* 04 March 2005 01:10:48 o'clock GMT
*/


// Utility descriptor structure.
public final class UtilityDescriptorHolder implements org.omg.CORBA.portable.Streamable
{
  public FoamXServer.UtilityDescriptor value = null;

  public UtilityDescriptorHolder ()
  {
  }

  public UtilityDescriptorHolder (FoamXServer.UtilityDescriptor initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = FoamXServer.UtilityDescriptorHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    FoamXServer.UtilityDescriptorHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return FoamXServer.UtilityDescriptorHelper.type ();
  }

}
