#!/bin/sh

set -x

(cd errorEstimation ; ./Allwmake)
(cd mesh ; ./Allwmake)
(cd surface ; ./Allwmake)
(cd parallelProcessing ; ./Allwmake)
(cd postProcessing ; ./Allwmake)
(cd preProcessing ; ./Allwmake)
(cd thermophysical ; ./Allwmake)
(cd miscellaneous ; ./Allwmake)
