#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
#cases="mixer2D linearValveLayers movingConeTopological"
cases="mixer2D"

tutorialPath=`dirname $0`/..
. $tutorialPath/CleanFunctions

for case in $cases
do
    cleanCase $case
done 
