#!/bin/sh

currDir=`pwd`
application=`basename $currDir`
#cases="mixer2D linearValveLayers movingConeTopological"
cases="mixer2D"

tutorialPath=`dirname $0`/..
. $tutorialPath/RunFunctions

for case in $cases
do
    runApplication blockMesh $case
    runApplication $application $case
done
