/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2005 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA

Class
    hashString

Description
    hashString function class specialisation for hashing strings.

\*---------------------------------------------------------------------------*/

#ifndef hashString_H
#define hashString_H

#include "Hash.H"
#include "string.H"

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

namespace Foam
{

/*---------------------------------------------------------------------------*\
                    Class Specialisation Hash<string> Declaration
\*---------------------------------------------------------------------------*/

template<>
class Hash<string>
{

public:

    Hash()
    {}

    label operator()(const string& key) const
    {
        const char* Key = key.c_str();

        register label hashVal = 0;
        while (*Key) hashVal = hashVal<<1 ^ *Key++;

        return hashVal;
    }

    label operator()(const string& key, const label tableSize) const
    {
        return mag(operator()(key)) % tableSize;
    }
};


typedef Hash<string> hashString;


// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

} // End namespace Foam

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //

#endif

// ************************************************************************* //
