#!/bin/sh

wmake libso zlib-1.2.1
wmake libso foamUser

FOAM_SRC_DIR=`pwd`

if [ "$WM_MPLIB" = "MPICH" -a ! -r $MPICH_ARCH_PATH/lib/libmpich.a -a ! -r $MPICH_ARCH_PATH/lib/libmpich.so ]
then
    
    cd $MPICH_PATH

        make distclean
        rm -rf $MPICH_ARCH_PATH
        rm util/machines/machines.*

        ./configure \
            --without-mpe \
            --disable-f77 \
            --disable-f90 \
            --disable-f90modules \
            --disable-c++ \
            --disable-mpedbg \
            --disable-devdebug \
            --disable-debug \
            --enable-sharedlib=$MPICH_ARCH_PATH/lib \
            --with-device=ch_p4 \
            -prefix=$MPICH_ARCH_PATH
        make
        make install
        make distclean

        if [ -r $MPICH_ARCH_PATH ]
        then
            cd $MPICH_ARCH_PATH/bin
            for file in *
            do
                sed s%$MPICH_ARCH_PATH%'$MPICH_ARCH_PATH'%g $file > temp.$$
                mv temp.$$ $file
                chmod ugo+rx $file
            done

            cd $MPICH_ARCH_PATH/lib

            if [ -r libmpich.so.1.0 ]
            then
                rm *.so
                ln -s libmpich.so.1.0 libmpich.so
            fi

            cd $MPICH_ARCH_PATH
        fi

    cd $FOAM_SRC_DIR
fi


if [ "$WM_MPLIB" = "LAM" -a ! -r $LAM_ARCH_PATH/lib/libmpi.a -a ! -r $LAM_ARCH_PATH/lib/libmpi.so ]
then

    cd $LAMHOME

        gmake distclean
        rm -rf $LAM_ARCH_PATH

        ./configure \
            --prefix=$LAM_ARCH_PATH \
            --enable-shared \
            --disable-static \
            --without-romio \
            --without-mpi2cpp \
            --without-profiling \
            --without-fc

        gmake
        gmake install
        gmake distclean

    cd $FOAM_SRC_DIR
fi

(cd $FOAM_SRC/OpenFOAM ; wmakeLnInclude . )

cd $FOAM_APP/utilities/miscellaneous
    wmake exe foamFlex
    cp foamFlex/FlexLexer.h $FOAM_SRC_DIR/OpenFOAM/lnInclude
cd $FOAM_SRC

(cd Pstream ; ./Allwmake)
wmake libso OpenFOAM

wmake libso lagrangian/basic

wmakeLnInclude meshTools
wmake libso triSurface
wmake libso meshTools

wmake libso sampling
wmake libso edgeMesh
wmake libso cfdTools

(cd finiteElement ; ./Allwmake)
wmake libso dynamicMesh
wmake libso engine

wmake libso ODE
wmake libso randomProcesses

(cd thermophysicalModels ; ./Allwmake)
(cd transportModels ; ./Allwmake)
(cd turbulenceModels ; ./Allwmake)
(cd LESmodels ; ./Allwmake)

(cd postProcessing ; ./Allwmake)

wmake libso lagrangian/dieselSpray

wmake libso finiteArea

wmake libso errorEstimation

wmake libso Gstream

(cd malloc ; ./Allwmake)

if [ ! -r $MICO_ARCH_PATH/lib/libmico${MICO_VERSION}.a ]
then
    cd $MICO_PATH
    gmake distclean
    ./configure --prefix=$MICO_ARCH_PATH --disable-shared --without-x
    gmake
    gmake install
    gmake distclean
    cd ..
fi

wmake libso foamUtil
