/*---------------------------------------------------------------------------*\
  =========                 |
  \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
   \\    /   O peration     |
    \\  /    A nd           | Copyright (C) 1991-2005 OpenCFD Ltd.
     \\/     M anipulation  |
-------------------------------------------------------------------------------
License
    This file is part of OpenFOAM.

    OpenFOAM is free software; you can redistribute it and/or modify it
    under the terms of the GNU General Public License as published by the
    Free Software Foundation; either version 2 of the License, or (at your
    option) any later version.

    OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
    ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
    FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
    for more details.

    You should have received a copy of the GNU General Public License
    along with OpenFOAM; if not, write to the Free Software Foundation,
    Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

\*---------------------------------------------------------------------------*/

#undef UNARY_FUNCTION
#undef UNARY_FUNCTION_N
#undef UNARY_FUNCTION_R

#undef UNARY_OPERATOR
#undef UNARY_OPERATOR_N
#undef UNARY_OPERATOR_R


#undef BINARY_FUNCTION_FF
#undef BINARY_FUNCTION_FT
#undef BINARY_FUNCTION_FR
#undef BINARY_FUNCTION_TF
#undef BINARY_FUNCTION_TT
#undef BINARY_FUNCTION_TR
#undef BINARY_FUNCTION_RF
#undef BINARY_FUNCTION_RT

#undef BINARY_FUNCTION_NN
#undef BINARY_FUNCTION_NR
#undef BINARY_FUNCTION_RN
#undef BINARY_FUNCTION_RR


#undef BINARY_TYPE_FUNCTION_SF
#undef BINARY_TYPE_FUNCTION_ST
#undef BINARY_TYPE_FUNCTION_SR
#undef BINARY_TYPE_FUNCTION_FS
#undef BINARY_TYPE_FUNCTION_TS
#undef BINARY_TYPE_FUNCTION_RS

#undef BINARY_TYPE_FUNCTION_NN
#undef BINARY_TYPE_FUNCTION_NR
#undef BINARY_TYPE_FUNCTION_RN
#undef BINARY_TYPE_FUNCTION_RR


#undef BINARY_OPERATOR_FF
#undef BINARY_OPERATOR_FT
#undef BINARY_OPERATOR_FR
#undef BINARY_OPERATOR_TF
#undef BINARY_OPERATOR_TT
#undef BINARY_OPERATOR_TR
#undef BINARY_OPERATOR_RF
#undef BINARY_OPERATOR_RT

#undef BINARY_OPERATOR_NN
#undef BINARY_OPERATOR_NR
#undef BINARY_OPERATOR_RN
#undef BINARY_OPERATOR_RR


#undef BINARY_TYPE_OPERATOR_SF
#undef BINARY_TYPE_OPERATOR_ST
#undef BINARY_TYPE_OPERATOR_SR
#undef BINARY_TYPE_OPERATOR_FS
#undef BINARY_TYPE_OPERATOR_TS
#undef BINARY_TYPE_OPERATOR_RS

#undef BINARY_TYPE_OPERATOR_NN
#undef BINARY_TYPE_OPERATOR_NR
#undef BINARY_TYPE_OPERATOR_RN
#undef BINARY_TYPE_OPERATOR_RR


// ************************************************************************* //
