#!/bin/bash -f
#------------------------------------------------------------------------------
# =========                 |
# \\      /  F ield         | OpenFOAM: The Open Source CFD Toolbox
#  \\    /   O peration     |
#   \\  /    A nd           | Copyright (C) 1991-2005 OpenCFD Ltd.
#    \\/     M anipulation  |
#-------------------------------------------------------------------------------
# License
#     This file is part of OpenFOAM.
#
#     OpenFOAM is free software; you can redistribute it and/or modify it
#     under the terms of the GNU General Public License as published by the
#     Free Software Foundation; either version 2 of the License, or (at your
#     option) any later version.
#
#     OpenFOAM is distributed in the hope that it will be useful, but WITHOUT
#     ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or
#     FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
#     for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with OpenFOAM; if not, write to the Free Software Foundation,
#     Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#
# Script
#     bashrc
#
# Description
#     Setup file for Paraview.
#     Sourced from .OpenFoam-?.?/bashrc
#
#------------------------------------------------------------------------------

if [ "$PS1" -a "$foamDotFile" ]; then
    if [ ! "$FOAM_SILENT" ]; then
        echo "Executing: $foamDotFile"
    fi
fi

export CMAKE_HOME=$WM_PROJECT_INST_DIR/$WM_ARCH/cmake-2.0.3

if [ -r $CMAKE_HOME ]; then
    export PATH=$PATH:$CMAKE_HOME/bin
fi

#export ParaView_VERSION=1.8.5
export ParaView_VERSION=2.2.0

export ParaView_INST_DIR=$WM_PROJECT_INST_DIR/$WM_ARCH/paraview-$ParaView_VERSION
#export ParaView_DIR=$ParaView_INST_DIR/lib/paraview-1.8
export ParaView_DIR=$ParaView_INST_DIR/lib/paraview-2.2

if [ -r $ParaView_INST_DIR ]; then
    export PV_INTERFACE_PATH=$FOAM_UTILITIES/postProcessing/graphics/PVFoamReader/PVFoamReader/Make

    export PATH=$PATH:$ParaView_INST_DIR/bin
    export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${ParaView_INST_DIR}/lib:${ParaView_INST_DIR}/lib/vtk
fi

if [ -r $ParaView_DIR ]; then
    export VTK_DIR=$ParaView_DIR/VTK
fi

# -----------------------------------------------------------------------------
