package FoamXServer.PatchToolServer;


/**
* FoamXServer/PatchToolServer/IPatchToolServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 22 June 2005 14:28:29 o'clock BST
*/


// ---------------------------------------------------------------------
public interface IPatchToolServer extends IPatchToolServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatchToolServer
