package FoamXServer.PatchToolServer;


/**
* FoamXServer/PatchToolServer/IPatchToolServer.java .
* Generated by the IDL-to-Java compiler (portable), version "3.1"
* from PatchTool.idl
* 03 March 2005 22:12:52 o'clock GMT
*/


// ---------------------------------------------------------------------
public interface IPatchToolServer extends IPatchToolServerOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface IPatchToolServer
